### ISSUE TITLE
shiny support via binder.

### ISSUE THREAD

**Issue by cboettig** [rocker-org/binder#14]
@yuvipanda Following up re your suggestion in #10 : the rocker container actually [already has a script to add shiny](https://github.com/rocker-org/rocker-versioned/tree/master/rstudio#add-shiny-server-on-start-up-with-e-addshiny), it just isn't run by default.  

adding the following RUN command: 

```
RUN export ADD=shiny && bash /etc/cont-init.d/add
``` 

to this Dockerfile will trigger this script.  Seems reasonable to add this in.

**Comment by cboettig** [comment]
(of course this would still need some work on the proxy side to integrate into binder proxy properly)

**Comment by cboettig** [comment]
added an experimental tag, `geospatial` that provides a more kitchen-sink base image.  (e.g. LaTeX support, geospatial libraries, java)

**Comment by brooksambrose** [comment]
re work on the proxy side, Shiny from within Rstudio Server's viewer was breaking and Yuvi addressed it with these PRs
https://github.com/jupyterhub/nbrsessionproxy/pull/25
https://github.com/jupyterhub/nbserverproxy/pull/17

**Comment by brooksambrose** [comment]
Would be cool to add an API call similar to `?urlpath=rstudio` like `?urlpath=shiny` that would allow an autolaunch of a shiny app directory.
