### ISSUE TITLE
Safari browser cannot open Terminal session in RStudio Server

### ISSUE THREAD

**Issue by brooksambrose** [rocker-org/binder#18]
On my own binderhub using an image based on rocker/binder:3.4.2, RStudio Server will not open a shell session in the new tabbed terminal window. `system()` still works. Terminal is working on my binder.org with the same repo though. When I check the pod log the last thing is a 403:

`[W 00:22:06.159 NotebookApp] 403 POST /user/w201rdada-portfolio-4jbqvvxy/rstudio/rpc/start_terminal (10.32.0.25)`

@yuvipanda any clue where to look to debug?

**Comment by brooksambrose** [comment]
Confirmed that this only occurs in Safari from my binderhub. Works as expected in Firefox and Chrome for Mac. I assume this has something to do with Safari security since my binderhub does not have SSL enabled right now.

**Comment by cboettig** [comment]
Closing for now since this sounds like a Safari issue.  please re-open if there's action we need to take on our end.
