### ISSUE TITLE
support servr

### ISSUE THREAD

**Issue by brooksambrose** [rocker-org/binder#19]
Currently in RStudio on Binder the command `servr::httd()`, which should serve a webpage in the RStudio Server viewer pane, is giving:

```
/p/4321/?viewer_pane=1 not found
```

I think this it may have been possible to open an arbitrary port before #13 when `nbserverproxy` was removed.

**Comment by cboettig** [comment]
is this still an issue?  at least `blogdown` and `xaringan` seem to be working fine in the studio viewer pane now or in serving webpages to a separate browser tab.  experience may be firewall dependent though.  re-open as needed
