### ISSUE TITLE
Base image: moving rocker/binder higher in the stack?

### ISSUE THREAD

**Issue by cboettig** [rocker-org/binder#21]
@yuvipanda @brooksambrose @choldgraf 

How would you feel about bumping the base image `FROM rocker/tidyverse` to instead start with `FROM rocker/geospatial`?  Obviously we cannot overcome everyone's system dependencies by pre-installing everything, but from our experience so far, an image like `verse` or `geospatial` (which builds on `verse`) and has a pretty common set of core system libraries to the point where most commonly used R packages at least in the data science space should install out of the box, while still maintaining a relatively small image.  

As we discover / are discovered by more communities this may grow/bifurcate, obviously it isn't an easy problem to provide preconfigured environment and ultimately there's no substitute for users/communities being able to just install what they need when they need it.  But from our experience in Rocker Project so far, I think our community-shaped stacks like `verse` or `geospatial` would make a good starting point

**Comment by yuvipanda** [comment]
I've no objections and I trust you to make the most useful choice for the R
community :)

**Comment by choldgraf** [comment]
+1 to what Yuvi said!

**Comment by cboettig** [comment]
This is done

**Comment by choldgraf** [comment]
🎉
