### ISSUE TITLE
R 3.4.3 not working

### ISSUE THREAD

**Issue by mrustl** [rocker-org/binder#25]
Using the [Dockerfile](https://github.com/binder-examples/dockerfile-rstudio/commit/ac505961a7987b9b351c3a4721ab39e8eacb398d) in the binder-examples/dockerfile-rstudio repo and changing the R version from 3.4.2 to 3.4.3 does not work.

![grafik](https://user-images.githubusercontent.com/11964451/37507553-62321946-28ef-11e8-8577-937b6a2c27ae.png)

**Comment by cboettig** [comment]
Thanks, looks like that tag failed to build, just re-queued it.  https://hub.docker.com/r/rocker/binder/builds/

Note that you can also just request `rocker/binder:latest` (equivalently, just `rocker/binder`) to get the current version of R (the `latest` tag has built successfully).
