### ISSUE TITLE
Use of rstudio and joyvan home directories

### ISSUE THREAD

**Issue by Robinlovelace** [rocker-org/binder#42]
It seems that RStudio starts by default in the RStudio directory but the user is joyan. I imagine this is just following Binder and RStudio Server conventions, but does it make sense and is it well documented?

A question that arose during my migration to rocker/binder:4.0.2 that finally seems to be working, with faster build times than before :tada:  

Check it out here: https://mybinder.org/v2/gh/robinlovelace/geocompr/master?urlpath=rstudio

I've simplified the Dockerfile compared with what it was previously but suspect it could be simpler still, do I really need to download the repo with wget? I don't fully understand how COPY works but imagine there's a neater way... Any feedback on this very gratefully received: https://github.com/Robinlovelace/geocompr/blob/master/.binder/Dockerfile

**Comment by cboettig** [comment]
Thanks, yeah, we could probably stick with "rstudio" as the default name, I'm not sure if there's a good argument to be made for sticking with joyvan as the user. @yuvipanda @choldgraf are we likely to break anything in so doing?

Re COPY/wget, etc, yeah, you have options.  COPY breaks cache, which could be good if you want to ensure the copy runs every time the container builds.  Otherwise I think your example is fine.  I think the `binder` image deserves a bit of an overhaul since the migration to `ubuntu`, (maybe tweaking the python setup etc), but I think is currently in queue behind us working out a `geospatial:devel` and probably the cuda:11 tags for the ML images, so we're a bit of a backlog!

**Comment by Robinlovelace** [comment]
Great reply @cboettig, sounds like you've got a lot on in the Rocker world. I think it would be more consistent to have everything in `/home/rstudio` but as you say not a priority. 

Re priorities for geospatial images.... 

Looking at the current state of Ubuntu Geo PPAs I am thinking that building directly on well maintained OSGeo images may give most boom-for-buck, e.g. building on this: https://github.com/OSGeo/gdal/blob/master/gdal/docker/ubuntu-full/Dockerfile

I'm thinking of giving it a go for geocompr/docker but let me know if you'd like me to try it here and/or open a separate issue or add further comments to https://github.com/rocker-org/geospatial/issues/31. Will be good to solve such issues as far upstream as possible.

**Comment by Robinlovelace** [comment]
Another perhaps more important issue I've found with the `rocker/binder:latest` images is that R sometimes never starts, even though RStudio starts-up no problem. I'm seeing this now here and it's been going for ~5 minutes: https://mybinder.org/v2/gh/robinlovelace/geocompr/master?urlpath=rstudio

> R is taking longer to start than usual

![image](https://user-images.githubusercontent.com/1825120/93707264-c3c3b980-fb24-11ea-8594-3538bb18f9c1.png)

Any ideas what is causing that message? I tried and succeeded in reproducing the issue on a local docker build but it seems intermittent. I may switch back to R 3.6.0 as that seems less prone to this issue, which I'm not sure how to debug... Again happy to open an issue but I'm struggling to get a fully reproducible example, other than the one shown in this Dockerfile: 

https://github.com/Robinlovelace/geocompr/blob/master/.binder/Dockerfile

**Comment by Robinlovelace** [comment]
Update, changing to R 3.6.3 and to the rstudio user, with the updated Dockerfile fixed the issue short term:

```
## Use a tag instead of "latest" for reproducibility
FROM rocker/binder:3.6.3

## Declares build arguments
ARG NB_USER
ARG NB_UID

## Copies your repo files into the Docker Container
USER root
## Enable this to copy files from the binder subdirectory
## to the home, overriding any existing files.
## Useful to create a setup on binder that is different from a
## clone of your repository
## COPY binder ${HOME}
RUN chown -R ${NB_USER} ${HOME}

## Run an install.R script, if it exists.
RUN R -e "remotes::install_github('geocompr/geocompkg')"

RUN wget https://github.com/robinlovelace/geocompr/archive/master.zip
RUN unzip master.zip
# COPY * /home/rstudio
RUN cp -Rv geocompr-master /home/rstudio/geocompr
RUN chown -Rv rstudio /home/rstudio

## Become normal user again
USER ${NB_USER}

RUN if [ -f install.R ]; then R --quiet -f install.R; fi

```

Next up, I'm going to try to change back to 4.0.2, with `RUN chown -Rv rstudio /home/rstudio` instead of `RUN chown -Rv joyvan /home/rstudio` which I suspect caused the issue...

**Comment by Robinlovelace** [comment]
OK, I've fixed the issue with R not loading in RStudio... The question/issue in the title and original post remains. Hope all this is useful!

**Comment by nuest** [comment]
@Robinlovelace didn't see your issue here, I'm also unsure about where to report issues with R 4.x - so linking my observations from https://github.com/rocker-org/rocker-versioned2/issues/88

**Comment by cboettig** [comment]
I think this should be resolved now with the working 4.x version as per #47
