### ISSUE TITLE
Site not launching?

### ISSUE THREAD

**Issue by Robinlovelace** [rocker-org/binder#43]
Just tried this and didn't seem to work: https://mybinder.org/v2/gh/rocker-org/binder/master?urlpath=rstudio

**Comment by louisaslett** [comment]
I think this is being discussed at the new repo here (adding for others like me who stumble into the old repo): rocker-org/rocker-versioned2#88

Perhaps an admin can close this issue?

**Comment by cboettig** [comment]
Yes, thanks @louisaslett , and apologies for the ongoing challenges here.  Let's see if the newest RStudio releases do anything to address these!

Folks, please see https://github.com/rocker-org/rocker-versioned2/issues/88
